// Tide Data
export const REQUEST_EPISODES = 'REQUEST_EPISODES'
export const REQUEST_EPISODES_SUCCESS = 'REQUEST_EPISODES_SUCCESS'
export const REQUEST_EPISODES_FAILURE = 'REQUEST_EPISODES_FAILURE'
export const FILTER_EPISODES = 'FILTER_EPISODES'

// Tide Actions
export const SEARCH_FILTER_UPDATE = 'SEARCH_FILTER_UPDATE'
export const SEARCH_FILTER_CLEAR = 'SEARCH_FILTER_CLEAR'
