// Tide Data
export const TIDE_REQUEST = 'TIDE_REQUEST'
export const TIDE_REQUEST_SUCCESS = 'TIDE_REQUEST_SUCCESS'
export const TIDE_REQUEST_FAILURE = 'TIDE_REQUEST_FAILURE'

// Tide Actions
export const SEARCH_FILTER_UPDATE = 'SEARCH_FILTER_UPDATE'
export const SEARCH_FILTER_CLEAR = 'SEARCH_FILTER_CLEAR'
